/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cabinet.gltf --transform 
Files: cabinet.gltf [1.84KB] > /Users/claire/dev/cabnet/model/cabinet/cabinet-transformed.glb [9.59KB] (-421%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cabinet(props) {
  const { nodes, materials } = useGLTF('/3D/cabinet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cabinet.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/3D/cabinet-transformed.glb')
