/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dvd_model_03.gltf --transform 
Files: dvd_model_03.gltf [10.58KB] > /Users/claire/dev/cabnet/model/deadbeat_ends_meet/gltf_export/dvd_model_03-transformed.glb [149.42KB] (-1312%)
*/

import React from 'react'
import { useGLTF, useFrame } from '@react-three/drei'

export function DVD_File(props, ref) {
  const { nodes, materials } = useGLTF('/3D/dvd_model_03-transformed.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Case_Back.geometry} material={materials.painted_concrete_02} position={[-0.068, 0, -0.001]} scale={[1, 1, 1.143]} />
      <group position={[0, 0, -0.003]}>
        <mesh geometry={nodes.Circle002.geometry} material={materials.DVD_Front} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.DVD_Side} />
        <mesh geometry={nodes.Circle002_2.geometry} material={materials.DVD_Back} />
      </group>
      <mesh geometry={nodes.Cover_Back.geometry} material={materials.DVD_Cover} position={[-0.068, 0, -0.001]} scale={[1.01, 1.01, 1.155]} />
    </group>
  )
}

useGLTF.preload('/3D/dvd_model_03-transformed.glb')